#!/bin/bash
# conda must be active to run this

phenos="pheno*"
SNPS="bcsnp_cd.vcf"
PHYLOSIM="phylosim_cd.tsv"

for pheno in $phenos
do
if test -f "res_${pheno}_lmm_ps.txt"; then
    echo "res_${pheno}_lmm_ps.txt exists."
else
    echo "Running LMM with phylosims for $pheno"
    pyseer --phenotypes ${pheno} --vcf ${SNPS} --similarity ${PHYLOSIM} --lmm --save-lmm _LMMCACHE_PENMIC_PSIM --cpu 4 --continuous > res_${pheno}_lmm_ps.txt
    cat <(echo "#CHR SNP BP minLOG10(P) log10(p) r^2") <(paste <(sed '1d' res_${pheno}_lmm_ps.txt | cut -d "_" -f 2) <(sed '1d' res_${pheno}_lmm_ps.txt | cut -f 4) |awk '{p = -log($2)/log(10); print "26",".",$1,p,p,"0"}' ) |tr ' ' '\t' > plt_${pheno}_lmm_ps.plot
fi
done

#echo "Running FEM with phylodistances"
#pyseer --phenotypes ${pheno} --vcf ${SNPS} --distances ${PHYLODIST} --cpu 4 --continuous > res_${pheno}_fem_pd.txt
#cat <(echo "#CHR SNP BP minLOG10(P) log10(p) r^2") <(paste <(sed '1d' res_${pheno}_fem_pd.txt | cut -d "_" -f 2) <(sed '1d' res_${pheno}_fem_pd.txt | cut -f 4) |awk '{p = -log($2)/log(10); print "26",".",$1,p,p,"0"}' ) |tr ' ' '\t' > plt_${pheno}_fem_pd.plot
#echo "###########################################################################################################################################################"

#echo "Running wg-enet with phylodistances"
#pyseer --phenotypes pheno_${pheno} --vcf ${SNPS} --distances ${PHYLODIST} --save-model ${pheno}_wgenet_pd --wg enet --cpu 4 --continuous > res_${pheno}_enet_pd.txt
#echo "###########################################################################################################################################################"


#pheno="pen.mic"
#SNPS="bcsnp_mic.vcf"
#PHYLOSIM="phylosim_mic.tsv"
#PHYLODIST="phylodist_mic.tsv"

#echo "Running LMM with phylosims"
#pyseer --phenotypes pheno_${pheno} --vcf ${SNPS} --similarity ${PHYLOSIM} --lmm --save-lmm _LMMCACHE_PENMIC_PSIM --cpu 4 --continuous > res_${pheno}_lmm_ps.txt
#cat <(echo "#CHR SNP BP minLOG10(P) log10(p) r^2") <(paste <(sed '1d' res_${pheno}_lmm_ps.txt | cut -d "_" -f 2) <(sed '1d' res_${pheno}_lmm_ps.txt | cut -f 4) |awk '{p = -log($2)/log(10); print "26",".",$1,p,p,"0"}' ) |tr ' ' '\t' > plt_${pheno}_lmm_ps.plot

#echo "Running FEM with phylodistances\n"
#pyseer --phenotypes pheno_${pheno} --vcf ${SNPS} --distances ${PHYLODIST} --cpu 4 --continuous > res_${pheno}_fem_pd.txt
#cat <(echo "#CHR SNP BP minLOG10(P) log10(p) r^2") <(paste <(sed '1d' res_${pheno}_fem_pd.txt | cut -d "_" -f 2) <(sed '1d' res_${pheno}_fem_pd.txt | cut -f 4) |awk '{p = -log($2)/log(10); print "26",".",$1,p,p,"0"}' ) |tr ' ' '\t' > plt_${pheno}_fem_pd.plot
#echo "###########################################################################################################################################################"

#echo "Running wg-enet with phylodistances"
#pyseer --phenotypes pheno_${pheno} --vcf ${SNPS} --distances ${PHYLODIST} --save-model ${pheno}_wgenet_pd --wg enet --cpu 4 --continuous > res_${pheno}_enet_pd.txt
#echo "###########################################################################################################################################################"


#pheno="cef.mic"
#printf "Now processing %s\n" ${pheno}

#echo "Running LMM with phylosims"
#pyseer --phenotypes pheno_${pheno} --vcf ${SNPS} --similarity ${PHYLOSIM} --lmm --save-lmm _LMMCACHE_CEFMIC_PSIM --cpu 4 --continuous > res_${pheno}_lmm_ps.txt
#cat <(echo "#CHR SNP BP minLOG10(P) log10(p) r^2") <(paste <(sed '1d' res_${pheno}_lmm_ps.txt | cut -d "_" -f 2) <(sed '1d' res_${pheno}_lmm_ps.txt | cut -f 4) |awk '{p = -log($2)/log(10); print "26",".",$1,p,p,"0"}' ) |tr ' ' '\t' > plt_${pheno}_lmm_ps.plot
#echo "###########################################################################################################################################################"

#echo "Running FEM with phylodistances\n"
#pyseer --phenotypes pheno_${pheno} --vcf ${SNPS} --distances ${PHYLODIST} --cpu 4 --continuous > res_${pheno}_fem_pd.txt
#cat <(echo "#CHR SNP BP minLOG10(P) log10(p) r^2") <(paste <(sed '1d' res_${pheno}_fem_pd.txt | cut -d "_" -f 2) <(sed '1d' res_${pheno}_fem_pd.txt | cut -f 4) |awk '{p = -log($2)/log(10); print "26",".",$1,p,p,"0"}' ) |tr ' ' '\t' > plt_${pheno}_fem_pd.plot
#echo "###########################################################################################################################################################"

#echo "Running wg-enet with phylodistances"
#pyseer --phenotypes pheno_${pheno} --vcf ${SNPS} --distances ${PHYLODIST} --save-model ${pheno}_wgenet_pd --wg enet --cpu 4 --continuous > res_${pheno}_enet_pd.txt
#echo "###########################################################################################################################################################"

