# Output directory name
output_dir: /mnt/5b763971-c1bf-48c1-961d-f2cee4492e43/Cloudstor/Research/Bacteria/Sim_h2/h0.7  # Path to the output directory

# Genome simulation parameters
num_species: 1000     # Number of samples in the simulated population
genome_length: 250000 # Length of the genome (.bp)
mutation_rate: 0.006   # Mutation rate - 
recomb_rate: 0.05      # Recombination rate - s pneumo
maf: 0.01             # Minor allele frequency threshold of rare alleles to be discarded
num_var: -1           # Number of simulated variants, if kept '-1', variant number will be solely a function of mutation rate
random_seed: 3157     # Random seed for reproducibility of results

# Phenotype simulation parameters
phen_type: quant                      # Type of simulated phenotype,'cc':binary case-control, 'quant': quantitative
num_causal_var: 10                    # Number of causal markers
causal_maf_min: 0.05                   # Minimum MinorAlleleFrequency of causal markers
causal_maf_max: 0.4                   # Maximum MinorAlleleFrequency of causal markers
causal_ld_max: 0.2                    # Maximum permitted r2 score between pairs of causal markers in window size of 1000 candidate causal markers meeting causal_maf_min and causal_maf_max thresholds
effect_size_odr: 5,10,15, 20, 25      # Effect sizes of causal markers (.odds ratios) (comma separated, must be a multiple of num_causal_var)
phen_replication: 100                 # Number of phenotype replication sets
heritability: 0.7                     # Heritability of phenotype
#disease_prevalence: 0.5               # Prevalence of phenotype
#case: 50                              # Use when phen_type='cc', case + control must not be bigger than num_species
#control: 50                           # Use when phen_type='cc', case + control must not be bigger than num_species
simvis_dpi: 100                       # Set the DPI for the simVis plot

# Linkage Disequilibrium plotting
plot_ld: False    # Generate the LD plot
snp_limit: 1000  # Number of SNPs randomly selected for plotting linkage map (Increasing this number will significatnly increase computation time)
ld_maf: 0.1      # Minimum MinorAlleleFrequency of markers for LD plotting (Lower this value, it is more difficult to estimate accurate r2 values between pairs of markers leading to more noisy plot)

# Runtime parameters
cores: 1         # Number of cores available for computations
latency_wait: 3  # Time to wait (in sec) after a job to ensure all files are present
